// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbdqgxqkrgmpewfycgaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiZHFneHFrcmdtcGV3ZnljZ2FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTE1OTMsImV4cCI6MjA3NDU2NzU5M30.q5d8Yb53GdbzodHkUI7RWLlb6RwpCDpDR9mcn61NUuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});